### PR TITLE
Fix failing tests and make sure CI runs all tests

### LINKED ISSUE #9: CI doesn't run all tests
When a Cargo workspace contains both the root package and other workspace members, `cargo test` by default runs tests only of the root package. In fact, `i3ipc-types` test fails since #7.

`cargo test --workspace` can be used to run tests on all workspace members as well as the root package but there is an issue.  Trying to build the whole workspace at once fails due to a compilation error. That is because Cargo tries to build the whole workspace with both `async-traits` and `async-std-traits` features enabled, and because those features are not additive (see <https://github.com/rust-lang/cargo/issues/4328>) it breaks. It should probably be a separate issue, though.

As a workaround, running `cargo test` in each directory will build each package separately, and doesn't merge features.

### PR DESCRIPTION
**Pull request by pcpthm**
Fix #9

### CODE REVIEW

**Comment by leshow** [comment]
Oh cool! Thank you! I'm guessing you want to see the async-std support released? I wasn't sure if anyone wanted it
