### ISSUE TITLE
CI doesn't run all tests

### ISSUE THREAD

**Issue by pcpthm** [leshow/tokio-i3ipc#9]
When a Cargo workspace contains both the root package and other workspace members, `cargo test` by default runs tests only of the root package. In fact, `i3ipc-types` test fails since #7.

`cargo test --workspace` can be used to run tests on all workspace members as well as the root package but there is an issue.  Trying to build the whole workspace at once fails due to a compilation error. That is because Cargo tries to build the whole workspace with both `async-traits` and `async-std-traits` features enabled, and because those features are not additive (see <https://github.com/rust-lang/cargo/issues/4328>) it breaks. It should probably be a separate issue, though.

As a workaround, running `cargo test` in each directory will build each package separately, and doesn't merge features.
